cs50w/project1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.entry, name="entry"),
    path("create", views.create, name="create"),
    path("random", views.rand, name="rand")
]

cs50w/project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

cs50w/project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

cs50w/project1/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from . import util
import random
import markdown2

class CreateForm(forms.Form):
    title = forms.CharField(label="title", required=False)
    content = forms.CharField(label="content", required=False)

class SearchForm(forms.Form):
    search = forms.CharField(label="search", required=False)

def subst(word,lst):
    ls = []
    len_word=len(word)
    len_lst=len(lst)
    for i in range(len_lst):
        for j in range(len(lst[i])-len_word+1):
            for k in range(len_word):
                if word[k] != lst[i][j+k]:
                    break
                if k == len_word-1:
                    ls += [lst[i]]
    return ls

def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["search"] in util.list_entries():
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[form.cleaned_data['search']]))
            return render(request, "encyclopedia/index.html", {
                "entries":subst(form.cleaned_data['search'], util.list_entries())
             })
    return render(request, "encyclopedia/index.html", {
            "entries":util.list_entries()
    })

def entry(request, name):
    if request.method=="POST":
        request.session["flag"]=True
        return render(request, "encyclopedia/create.html", {
            "name" : name,
            "content" : util.get_entry(name)
        })
    return render(request, "encyclopedia/entry.html", {
        "name": name,
        "content": util.get_entry(name)
    })

def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["title"] not in util.list_entries():
                util.save_entry(form.cleaned_data["title"], markdown2.markdown(form.cleaned_data["content"]))
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[form.cleaned_data["title"]]))
            else: 
                if request.session.pop("flag", False):
                    return render(request, "encyclopedia/entry.html", {
                        "name": form.cleaned_data["title"],
                        "content": markdown2.markdown(form.cleaned_data["content"])
                    })
                else:
                    return HttpResponse("error")
        else:
            return render(request, "encyclopedia/create.html", {
            })
    return render(request, "encyclopedia/create.html", {
    })

def rand(request):
    entries = util.list_entries()
    random_title = random.choice(entries)
    return HttpResponseRedirect(reverse("encyclopedia:entry", 
                args=[random_title]))

cs50w/project1/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a new entry
{% endblock %}

{% block body %}
<form action="{% url 'encyclopedia:create' %}" method="post">
    {% csrf_token %}
    <label for="id_title">Title</label>
    <input id="id_title" type="text" name="title" required pattern=".*\S.*" value={{ name }}>

    <label for="id_content"></label>
    <textarea id="id_content" name="content" rows="4" cols="30">{{ content }}</textarea>
    <button type="submit" value="Submit">Save</button>
</form>

{% endblock %}

cs50w/project1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>{{ name }}</h1>

{{ content|safe }}
<br>
<br>
<form method="post">
    {% csrf_token %}
    <button type="submit" name="edit">Edit</button>
</form>
{% endblock %}

cs50w/project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>SearchWiki</h1>

<ul>
    {% for entry in entries %}
        {% if entry %}
        <li>
            <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
        {% endif %}
            {% empty %}
                <li>No match.</li>
        </li>
    {% endfor %}


</ul>

{% endblock %}

cs50w/project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" required pattern = ".*\S.*" type="text" name="search" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:rand' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>